// Code generated by internal/apidoc/cmd/apidoc; DO NOT EDIT.

package addon

import "daddy-cull/next/internal/api"

// The comments on this package's types and fields, for the API reference.
func init() {
	api.AddDocs(map[string]string{
		"daddy-cull/next/internal/addon.BuiltIn":              "BuiltIn is an addon that comes with Cull.",
		"daddy-cull/next/internal/addon.BuiltIn.Default":      "Default is whether it is on before anyone has turned it on or off: usually whether there is anything for it to show.",
		"daddy-cull/next/internal/addon.BuiltIn.Status":       "Status says whether it has what it needs and what it holds.",
		"daddy-cull/next/internal/addon.Choice":               "Choice is the body that turns an addon on or off.",
		"daddy-cull/next/internal/addon.Manifest":             "Manifest describes an addon. An addon of your own gives it as addon.json.",
		"daddy-cull/next/internal/addon.Manifest.Description": "Description says more: what it adds, and what it needs.",
		"daddy-cull/next/internal/addon.Manifest.ID":          "ID is the addon's name in lower case with hyphens. It is also the name of its folder.",
		"daddy-cull/next/internal/addon.Manifest.Needs":       "Needs lists what it needs to work, in words.",
		"daddy-cull/next/internal/addon.Manifest.Permissions": "Permissions are what the addon's key may do beyond reading: review, bin, delete or settings. Cull's own addons are part of Cull and ask for none.",
		"daddy-cull/next/internal/addon.Manifest.Summary":     "Summary says in one sentence what it is for.",
		"daddy-cull/next/internal/addon.Manifest.Work":        "Work lists what it does in the background while it is on, in words.",
		"daddy-cull/next/internal/addon.Page":                 "Page is a page an addon adds to the sidebar.",
		"daddy-cull/next/internal/addon.Page.ID":              "ID names the page within its addon, in lower case with hyphens.",
		"daddy-cull/next/internal/addon.Page.Icon":            "Icon is a Material Symbols name from the set Cull ships; an unknown one is drawn as a puzzle piece.",
		"daddy-cull/next/internal/addon.Page.Path":            "Path is where the page is in Cull. For an addon of your own it is /addons/<addon>/<page> and is filled in by Cull.",
		"daddy-cull/next/internal/addon.Page.Section":         "Section is where in the sidebar it goes: collections, sync or tools.",
		"daddy-cull/next/internal/addon.Page.URL":             "URL is the page an addon of your own serves, which Cull shows inside its frame. Cull's own addons have none.",
		"daddy-cull/next/internal/addon.Registry":             "Registry knows every addon and whether it is on.",
		"daddy-cull/next/internal/addon.Status":               "Status says whether an addon has what it needs.",
		"daddy-cull/next/internal/addon.Status.Detail":        "Detail says what it holds, or what it waits for, in a sentence.",
		"daddy-cull/next/internal/addon.Status.State":         "State is ready, setup when it waits for something to be set up, or problem when it cannot work.",
		"daddy-cull/next/internal/addon.View":                 "View is an addon as the Addons page shows it.",
		"daddy-cull/next/internal/addon.View.Chosen":          "Chosen says someone turned it on or off, rather than it being on or off by default.",
		"daddy-cull/next/internal/addon.View.Folder":          "Folder is where an addon of your own lives, relative to the addons folder; its key is written there as \"key\" when it is turned on.",
		"daddy-cull/next/internal/addon.View.Problem":         "Problem says why an addon of your own cannot be loaded.",
		"daddy-cull/next/internal/addon.View.Routes":          "Routes counts its API routes, which the API reference lists.",
	})
}
