// Package apidoc reads the comments on a package's exported types and their
// fields and writes them out as a Go file, so the API reference describes a
// field in the words its code does.
package apidoc

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/doc"
	"go/doc/comment"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
)

// Generate reads the package in dir, whose import path is pkgPath, and
// returns the source of a file in that package that registers its comments.
func Generate(dir, pkgPath string) ([]byte, error) {
	fset := token.NewFileSet()
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var files []*ast.File
	var pkgName string
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") || name == OutputName {
			continue
		}
		file, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, parser.ParseComments)
		if err != nil {
			return nil, err
		}
		pkgName = file.Name.Name
		files = append(files, file)
	}
	found := map[string]string{}
	for _, file := range files {
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}
			for _, spec := range gen.Specs {
				ts := spec.(*ast.TypeSpec)
				if !ts.Name.IsExported() {
					continue
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}
				typeDoc := ts.Doc
				if typeDoc == nil && len(gen.Specs) == 1 {
					typeDoc = gen.Doc
				}
				if text := clean(typeDoc); text != "" {
					found[pkgPath+"."+ts.Name.Name] = text
				}
				for _, field := range st.Fields.List {
					text := clean(field.Doc)
					if text == "" {
						text = clean(field.Comment)
					}
					if text == "" {
						continue
					}
					for _, name := range field.Names {
						if name.IsExported() {
							found[pkgPath+"."+ts.Name.Name+"."+name.Name] = text
						}
					}
				}
			}
		}
	}
	keys := make([]string, 0, len(found))
	for k := range found {
		keys = append(keys, k)
	}
	slices.Sort(keys)
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by internal/apidoc/cmd/apidoc; DO NOT EDIT.\n\npackage %s\n\nimport \"daddy-cull/next/internal/api\"\n\n", pkgName)
	b.WriteString("// The comments on this package's types and fields, for the API reference.\nfunc init() {\n\tapi.AddDocs(map[string]string{\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "\t\t%s: %s,\n", strconv.Quote(k), strconv.Quote(found[k]))
	}
	b.WriteString("\t})\n}\n")
	return format.Source(b.Bytes())
}

// OutputName is the file Generate's output is written to.
const OutputName = "apidoc_gen.go"

// clean turns a comment into running text. A comment that names the field
// first, as Go comments do, keeps its words; line breaks inside a paragraph
// are joined and paragraphs kept apart.
func clean(group *ast.CommentGroup) string {
	if group == nil {
		return ""
	}
	var p doc.Package
	text := group.Text()
	parsed := p.Parser().Parse(text)
	var paragraphs []string
	for _, block := range parsed.Content {
		switch block := block.(type) {
		case *comment.Paragraph:
			var words strings.Builder
			for _, t := range block.Text {
				words.WriteString(plain(t))
			}
			paragraphs = append(paragraphs, strings.Join(strings.Fields(words.String()), " "))
		default:
			paragraphs = append(paragraphs, strings.TrimSpace(string(p.Printer().Text(&comment.Doc{Content: []comment.Block{block}}))))
		}
	}
	return strings.Join(paragraphs, "\n\n")
}

func plain(t comment.Text) string {
	switch t := t.(type) {
	case comment.Plain:
		return string(t)
	case comment.Italic:
		return string(t)
	case *comment.Link:
		return words(t.Text)
	case *comment.DocLink:
		return words(t.Text)
	}
	return ""
}

func words(parts []comment.Text) string {
	var s strings.Builder
	for _, part := range parts {
		s.WriteString(plain(part))
	}
	return s.String()
}
